# Generated by Django 6.1.1 on 2026-10-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0002_alter_interview_created_by'),
        ('profiles', '0002_alter_studentprofile_backlogs_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('profile',), name='unique_default_placement_resume_per_student'),
        ),
    ]
