from django.urls import path

from .views import (
    apply_job,
    certification_add,
    certification_delete,
    certification_edit,
    company_dashboard,
    dashboard_home,
    internship_add,
    internship_delete,
    internship_edit,
    job_posting_create,
    login_view,
    logout_view,
    mark_notification_read,
    officer_dashboard,
    placement_notifications,
    placement_report_csv,
    placement_reports,
    profile_detail,
    profile_form,
    project_add,
    project_delete,
    project_edit,
    root_redirect,
    skill_add,
    skill_delete,
    skill_edit,
    student_dashboard,
    update_application_status,
)

urlpatterns = [
    path('', root_redirect, name='root_redirect'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('dashboard/', dashboard_home, name='dashboard'),
    path('dashboard/student/', student_dashboard, name='student_dashboard'),
    path('dashboard/company/', company_dashboard, name='company_dashboard'),
    path('dashboard/officer/', officer_dashboard, name='officer_dashboard'),
    path('jobs/apply/<int:job_id>/', apply_job, name='apply_job'),
    path('jobs/create/', job_posting_create, name='job_posting_create'),
    path('applications/<int:app_id>/update-status/', update_application_status, name='update_application_status'),
    path('notifications/', placement_notifications, name='placement_notifications'),
    path('notifications/read/<int:notif_id>/', mark_notification_read, name='mark_notification_read'),
    path('reports/placement/', placement_reports, name='placement_reports'),
    path('reports/placement/csv/', placement_report_csv, name='placement_report_csv'),
    path('profile/', profile_form, name='profile_form'),
    path('profile/view/', profile_detail, name='profile_detail'),
    path('skills/add/', skill_add, name='skill_add'),
    path('skills/edit/<int:pk>/', skill_edit, name='skill_edit'),
    path('skills/delete/<int:pk>/', skill_delete, name='skill_delete'),
    path('certifications/add/', certification_add, name='certification_add'),
    path('certifications/edit/<int:pk>/', certification_edit, name='certification_edit'),
    path('certifications/delete/<int:pk>/', certification_delete, name='certification_delete'),
    path('projects/add/', project_add, name='project_add'),
    path('projects/edit/<int:pk>/', project_edit, name='project_edit'),
    path('projects/delete/<int:pk>/', project_delete, name='project_delete'),
    path('internships/add/', internship_add, name='internship_add'),
    path('internships/edit/<int:pk>/', internship_edit, name='internship_edit'),
    path('internships/delete/<int:pk>/', internship_delete, name='internship_delete'),
]
